### ISSUE TITLE
Замечания по Shapes

### ISSUE THREAD

**Issue by AniSkyWorker** [mqxim/oop#10]
- [x] интерфейс не должен содержать внутри себя никакую логику, он служит для создания декларативных абстракций, для логики завести класс BaseShape, для SolidShape тоже самое
- [x] GetFillColor должен быть помечен как виртуальный
- [x] для ICanvas нужно убрать конструктор и удалить cpp
- [x] простым классам виртуальный деструктор не нужен
- [x] стоит переименовать StringOperations, сейчас название ничего не говорит о содержимом
- [x] выпилить ненужные инструкции к sfml, например активация окна, display стоит вынести в метод Redraw
- [x] убрать инициализацию фигур первым элементом массива при поиске периметра и площади

k = 0.7

**Comment by mqxim** [comment]
1. Доделал наследование для базового класса.
2. Пометил метод как виртуальный.
3. Для интерфейсов убрал конструкторы и cpp файлы.
4. Убрал виртуальные деструкторы для простых классов.
5. Переименовал StringOperations в Uint32ToHex

**Comment by mqxim** [comment]
6. Убрал инициализациб фигур.

**Comment by mqxim** [comment]
7. Перенес метод display в другое место

**Comment by alexey-malov** [comment]
```
2>c1xx : fatal error C1083: Cannot open source file: '..\Geometry\StringOperations.cpp': No such file or directory
```

- [ ] Тесты не собираются

**Comment by alexey-malov** [comment]
- [ ] Методы, не меняющие состояние объектов, должны быть константными

**Comment by alexey-malov** [comment]
- [ ] Если в базовом классе деструктор был объявлен виртуальным, то он остаётся виртуальным во всех классах-наследниках

**Comment by alexey-malov** [comment]
- [ ] ISolidShape должен наследоваться от IShape

**Comment by alexey-malov** [comment]
k=0,5

**Comment by mqxim** [comment]
Исправлено
