### ISSUE TITLE
Замечания по InvertMatrix

### ISSUE THREAD

**Issue by alexey-malov** [mqxim/oop#2]
- [x] Если при проверке программы обнаружена ошибка, тест должен выйти с ненулевым кодом возврата.

**Comment by alexey-malov** [comment]
```c++
bool InitializeMatrix(int argc, char* argv[], Matrix &matrix)
{
	if (argc != 2)
	{
		return false;
	}

	std::ifstream input(argv[1]);

	...

	return false;
}
```

- [ ] argc/argv лучше проверить в main либо в функции для разбора аргументов. В функцию считывания матрицы из файла лучше передавать путь к файлу. При этом функция, считывающая матрицу из потока, может остаться

**Comment by alexey-malov** [comment]
```c++
bool ReadMatrixFromFile(std::ifstream& input, Matrix &matrix)
{
```

- [ ] Тут лучше принимать std::istream&

**Comment by alexey-malov** [comment]
```c++
	int lineNumber = 0;

	int inputLineQuantity = 0;
```

- [ ] Нельзя ли обойтись одной переменной

**Comment by alexey-malov** [comment]
- [ ] Строка матрицы - не line, а row

**Comment by alexey-malov** [comment]
```c++
	if (inputLineQuantity != INPUT_LINES_QUANTIY)
	{	
		return false;
	}
```

- [ ] Почему бы не сравнить с количеством строк матрицы. И вообще не использовать for для чтения известного количества строк матрицы. Если строк не будет хватать, мы можем выйти с ошибкой, если будут лишние, то ничего страшного

**Comment by alexey-malov** [comment]
- [ ] Код чтения строк матрицы сложен

**Comment by alexey-malov** [comment]
- [ ] Излишне проверять строку при помощи регулярного выражения. Если stof не сможет прочитать строку, то выбросит исключение. Либо мы можем считать строку из файла в строку, а потом создать istringstream из этой строки, а дальше уже считывать float-ы из этого стрима при помощи оператора `>>`, проверяя ошибки чтения

**Comment by alexey-malov** [comment]
```c++
void TransposeMatrix3x3(Matrix& matrix)
{
	for (int i = 0; i < SQUARE_MATRIX_SIZE; i++)
	{
		for (int g = 0; g < SQUARE_MATRIX_SIZE; g++)
		{
			if (i <= g)
			{
				auto num = matrix[i][g];
				matrix[i][g] = matrix[g][i];
				matrix[g][i] = num;
			}
		}
	}
}
```

- [ ] Избавиться от if

- [ ] Используйте std::swap для обмена

**Comment by alexey-malov** [comment]
```c++
Matrix GetComplementMatrix3x3(const Matrix& matrix)
{
	Matrix outMatrix = { 0 };

	for (int i = 0; i < SQUARE_MATRIX_SIZE; i++)
	{
		for (int g = 0; g < SQUARE_MATRIX_SIZE; g++)
		{
			outMatrix[i][g] =  float(std::pow(-1, i + g + 2)) * GetComplementOfMatrix3x3(matrix, i, g);
		}
	}

	return outMatrix;
}
```

- [ ] Вместо использования возведения в степень воспользуйтесь тем, что этот коэффициент просто меняет знак.

**Comment by alexey-malov** [comment]
```c++
void PrintMatrix(const Matrix& matrix)
{
	for (int i = 0; i < SQUARE_MATRIX_SIZE; i++)
	{
		for (int g = 0; g < SQUARE_MATRIX_SIZE; g++)
		{
			printf("%.3f", matrix[i][g]);
			std::cout << " ";
		}
		std::cout << std::endl;
	}
}
```

- [ ] Не используйте printf
https://en.cppreference.com/w/cpp/io/manip/setprecision
https://en.cppreference.com/w/cpp/io/manip/fixed

**Comment by alexey-malov** [comment]
- [ ] Если матрица вырожденная, то надо вывести об этом сообщение

**Comment by alexey-malov** [comment]
- [ ] Выделить функцию TryInvertMatrix, возвращающую bool. Вариант - вернуть std::optional
https://www.youtube.com/watch?v=QhwPSRiPmUA

**Comment by mqxim** [comment]
1. Переделал функцию int main(). В ней происходит проверка массива строк argv.
2. Функция ReadMatrixFromFile теперь принимает путь к файлу и возвращает std::nullopt в случае неудачи чтения матрицы
3. Больше не используются регулярные выражения для проверки корректности строки, теперь значения читаются из istringstream
4. Упрощен модуль с функциями матриц.

**Comment by mqxim** [comment]
5. Printf больше не используется для вывода 3 знаков после запятой. Используется:
'''c++
std::cout << std::setprecision(3) << std::fixed << matrix[i][g] << " "; 
'''

**Comment by AniSkyWorker** [comment]
- [] в функции ```InitializeMatrixRow``` стоит использовать либо ручное чтение + std::stof, либо чтение из stringstream, с выставленным флагом исключений(переменную контейнер объявлять вне цикла)
-[] при чтении из файла использовать константу, определяющую размер матрицы, а не отдельную
-[] написать тесты на несуществующий файл, матрицы неправильной размерности, вырожденные матрицы

**Comment by mqxim** [comment]
Поправил ошибки
